#!/usr/bin/env bash
#
# configure-gbrain.sh — configure brain, env, and health checks (k8s pod start phase).
#
# Idempotent: safe to re-run on pod restart. Requires a prior install-gbrain.sh run.
#
# Required env:
#   OPENROUTER_API_KEY
#
# Optional env: see bootstrap-gbrain.sh header (brain repo, template, models, etc.)
#
# Exit codes:
#   0   configure complete + smoke probes green
#   1   missing required env
#   2   gbrain not installed
#   3   gbrain init / doctor / embed failure
#   4   OpenRouter probe failure

set -euo pipefail

log() { echo "[configure-gbrain $(date -u +%FT%TZ)] $*" >&2; }
fail() { log "ERROR: $*"; exit "${2:-1}"; }

gbrain_bootstrap_init_env() {
  REPO="${GBRAIN_REPO:-https://github.com/AliAzaz/gbrain.git}"
  BRANCH="${GBRAIN_BRANCH:-master}"
  INSTALL_DIR="${GBRAIN_INSTALL_DIR:-/opt/gbrain}"
  BRAIN_DATA="${GBRAIN_HOME:-/data/gbrain}"
  export GBRAIN_HOME="$BRAIN_DATA"
  export HOME="${HOME:-/root}"
  GBRAIN_EMBEDDING_MODEL="${GBRAIN_EMBEDDING_MODEL:-openrouter:openai/text-embedding-3-large}"
  GBRAIN_EMBEDDING_DIMENSIONS="${GBRAIN_EMBEDDING_DIMENSIONS:-1536}"
  GBRAIN_CHAT_MODEL="${GBRAIN_CHAT_MODEL:-openrouter:anthropic/claude-sonnet-4.5}"
  GBRAIN_EXPANSION_MODEL="${GBRAIN_EXPANSION_MODEL:-openrouter:openai/gpt-4o-mini}"
  export GBRAIN_EMBEDDING_MODEL GBRAIN_EMBEDDING_DIMENSIONS GBRAIN_CHAT_MODEL GBRAIN_EXPANSION_MODEL
  mkdir -p "$BRAIN_DATA" "$(dirname "$INSTALL_DIR")"
}

require_gbrain_installed() {
  if [[ ! -f "$INSTALL_DIR/src/cli.ts" ]]; then
    fail "gbrain not installed at $INSTALL_DIR (missing src/cli.ts); run scripts/bootstrap/install-gbrain.sh first" 2
  fi
}

persist_gbrain_file_config() {
  local config_path="$BRAIN_DATA/.gbrain/config.json"
  local db_path="$BRAIN_DATA/.gbrain/brain.pglite"
  mkdir -p "$(dirname "$config_path")"
  CONFIG_PATH="$config_path" \
  DB_PATH="$db_path" \
  EMBED_MODEL="$GBRAIN_EMBEDDING_MODEL" \
  EMBED_DIMS="$GBRAIN_EMBEDDING_DIMENSIONS" \
  CHAT_MODEL="$GBRAIN_CHAT_MODEL" \
  EXPANSION_MODEL="$GBRAIN_EXPANSION_MODEL" \
  bun -e '
    const fs = require("fs");
    const path = require("path");
    const p = process.env.CONFIG_PATH;
    let cfg = {};
    try { cfg = JSON.parse(fs.readFileSync(p, "utf8")); } catch {}
    cfg.engine = cfg.engine || "pglite";
    if (!cfg.database_path) cfg.database_path = process.env.DB_PATH;
    cfg.embedding_model = process.env.EMBED_MODEL;
    cfg.embedding_dimensions = parseInt(process.env.EMBED_DIMS, 10);
    cfg.expansion_model = process.env.EXPANSION_MODEL;
    cfg.chat_model = process.env.CHAT_MODEL;
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, JSON.stringify(cfg, null, 2) + "\n", { mode: 0o600 });
  ' || fail "failed to persist OpenRouter routing to $config_path" 3
  log "Persisted OpenRouter routing to $config_path (survives shells without GBRAIN_EMBEDDING_MODEL)"
}

# -- scaffold_brain_template <target-dir> -------------------------------------
# Creates the MECE directory structure described in
# docs/GBRAIN_RECOMMENDED_SCHEMA.md inside <target-dir>:
#   - 20 knowledge directories, each with a README.md resolver
#   - top-level RESOLVER.md (master decision tree)
#   - schema.md (page conventions + person/company/meeting templates)
#   - log.md + index.md
#   - .raw/ sidecars under people/ and companies/
#   - initial git commit so the brain is version-controllable from day one
# Idempotent at the directory level — never clobbers an existing brain repo.
scaffold_brain_template() {
  local target="$1"
  local author_name="${GBRAIN_AUTHOR_NAME:-GBrain Bootstrap}"
  local author_email="${GBRAIN_AUTHOR_EMAIL:-bootstrap@gbrain.local}"

  if [[ -d "$target/.git" ]] || [[ -f "$target/RESOLVER.md" ]]; then
    log "Brain template already exists at $target (skipping scaffold)"
    return 0
  fi

  log "Scaffolding MECE brain template at $target..."
  mkdir -p "$target"
  (
    cd "$target"
    git init -q
    git config user.name "$author_name"
    git config user.email "$author_email"

    # ---- top-level files ---------------------------------------------------
    cat > .gitignore <<'EOF'
.gbrain/
*.tmp
*.swp
.DS_Store
node_modules/
EOF

    cat > README.md <<'EOF'
# Brain

LLM-maintained knowledge base. Structured markdown wiki of people,
companies, deals, meetings, projects, ideas, and concepts — owned and
maintained by your agent.

Read `RESOLVER.md` before creating any page. Read `schema.md` for page
conventions and templates. Every directory has a `README.md` resolver
explaining what goes there and what does NOT.

Generated by `bootstrap-gbrain.sh` from
`docs/GBRAIN_RECOMMENDED_SCHEMA.md` (v0.5.0). Customize freely — the
structure is yours to evolve.
EOF

    cat > RESOLVER.md <<'EOF'
# Resolver — Master Decision Tree

When creating or filing any new page, walk this tree. Every piece of
knowledge has EXACTLY ONE primary home.

## Decision tree — what is the primary subject?

1. A specific named person → `people/`
2. A specific organization (company, fund, nonprofit, gov body) → `companies/`
3. A financial transaction with terms and a decision → `deals/`
4. A record of a specific meeting/call → `meetings/`
5. Something being actively built (has a repo/spec/team) → `projects/`
6. A raw possibility nobody is building yet → `ideas/`
7. A reusable mental model or thesis → `concepts/`
8. A piece of prose publishable as a standalone work → `writing/`
9. Your institution's strategy/org/internal dynamics → `org/`
10. Political or civic landscape (policy, elections, gov) → `civic/`
11. Public narrative / content operations → `media/`
12. A major life program (enduring domain, many projects) → `programs/`
13. Domestic operations (properties, logistics, household) → `household/`
14. Private notes (health, personal reflection) → `personal/`
15. Hiring pipeline (candidate evals, role specs) → `hiring/`
16. A reusable LLM prompt → `prompts/`
17. A raw data import or snapshot → `sources/`
18. Agent deliverables (briefings, digests, research) → `agent/`
19. Unsorted / quick capture (you don't know yet) → `inbox/`
20. Dead / no longer relevant → `archive/`

## Disambiguation tiebreakers

- **Person vs. Company:** Is it about THEM as a human (beliefs,
  relationship, trajectory)? → people/. Is it about the ORG they run? →
  companies/. Both pages link to each other.
- **Concept vs. Idea:** Could you TEACH it as a framework? Concept.
  Could you BUILD it? Idea.
- **Concept vs. Personal:** Would you share it in a professional talk?
  Concept. Is it private reflection? Personal.
- **Idea vs. Project:** Is anyone working on it? Yes → project. No →
  idea. The graduation moment is when work starts.
- **Writing vs. Concepts:** Concept is distilled (~200 words). Writing
  is developed prose (argument, narrative).
- **Writing vs. Media:** Writing is the ARTIFACT (the essay). Media is
  the PRODUCTION + DISTRIBUTION infrastructure.
- **Org vs. Programs:** org/ is institutional knowledge ABOUT your
  organization. programs/ is your personal role + priorities WITHIN it.
- **Civic vs. People:** Political figures get people/ pages. Their
  legislative agenda + civic positioning goes in civic/.
- **Household vs. Personal:** Would a PA execute on it? → household
  (operational). Private reflection? → personal (inner life).
- **Sources vs. .raw/:** Per-entity enrichment data → .raw/ sidecar
  next to the entity. Bulk multi-entity imports → sources/.

## MECE check

If something genuinely doesn't fit any category, file it in `inbox/`
and flag it. That's a signal the schema needs to evolve. Don't force
the wrong category.
EOF

    cat > schema.md <<'EOF'
# Schema — Page Conventions

Every page has TWO layers separated by `---`:

- **Above the line — Compiled Truth.** Always current, rewritten on
  every new signal. Starts with a one-paragraph executive summary.
  Includes State, Open Threads, See Also.
- **Below the line — Timeline.** Append-only. Reverse-chronological.
  Each entry: date, source, what happened.

## Person template

```markdown
# Person Name

> Executive summary: who they are, why they matter, what you should
> know walking into any interaction with them.

## State
- **Role:** Current title
- **Company:** Current org
- **Relationship:** To you (friend, colleague, investor, etc.)
- **Key context:** 2-4 bullets of what matters right now

## What They Believe
- [Belief] — observed: [tweet/meeting/article, date]
- [Belief] — self-described: [interview/bio, date]
- [Belief] — inferred: [pattern across N interactions, confidence: high/medium/low]

## What They're Building
## What Motivates Them
## Communication Style
## Hobby Horses
## Assessment
- **Strengths:**
- **Gaps:**
- **Net read:**
- **Confidence:** high (5+ interactions) / medium (2-4) / low (1)
- **Last assessed:** YYYY-MM-DD

## Trajectory
## Relationship
## Contact
## Network
## Open Threads

---

## Timeline
- **YYYY-MM-DD** | Source — What happened.
```

## Company template

```markdown
# Company Name

> What they do, stage, why they matter.

## State
- **What:** One-line description
- **Stage:** Seed / Series A / Growth / Public
- **Key people:** Names with links to people pages
- **Key metrics:** Revenue, headcount, funding
- **Connection:** How they relate to your world

## Open Threads

---

## Timeline
```

## Meeting template

```markdown
# Meeting Title

> YOUR analysis — not a copy of the AI meeting notes.
> What matters given everything else going on.

## Attendees
## Key Decisions
## Action Items
## Connections to other brain pages

---

## Full Transcript
```

## Canonical slugs

- People: `first-last.md` (lowercase, hyphens)
- Companies: `company-name.md`
- Collisions: disambiguate (`david-liu-crustdata.md`)

The filename IS the entity identity. All cross-references use the slug.

## Epistemic discipline (people pages)

- Every claim cites its source. Three source types: `observed`,
  `self-described`, `inferred`.
- Confidence tracks interaction count. One meeting = low. Five+ = high.
- Never generalize from a single data point.
- User corrections override everything.
EOF

    # log.md (append-only chronological record)
    cat > log.md <<EOF
# Log

Chronological record of brain operations. Append-only.

- **$(date -u +%Y-%m-%d) | bootstrap** — MECE template scaffolded.
EOF

    # index.md (content catalog, rebuild periodically)
    cat > index.md <<'EOF'
# Index

Content catalog. Rebuild periodically with `gbrain stats` /
`gbrain doctor` or by re-walking the directory tree.

(Empty on first scaffold — populates as pages are created.)
EOF

    # ---- MECE directories with per-dir READMEs (resolvers) -----------------
    _readme() {
      local dirname="$1"
      shift
      mkdir -p "$dirname"
      cat > "$dirname/README.md" <<EOF
# $dirname/

$@
EOF
      # .gitkeep so git tracks the empty directory
      touch "$dirname/.gitkeep"
    }

    _readme "people" \
      "One page per human being.

## What goes here
- Anyone you've had a 1:1 or small-group meeting with
- Key colleagues, partners, direct collaborators
- Anyone with a strong working relationship
- Family, close friends, inner circle

## What does NOT go here
- The organizations they work for → \`companies/\`
- Hiring candidates being actively evaluated → \`hiring/\`
- Random names from mass guest lists with no interaction
- Political figures' civic positioning → \`civic/\` (but they still
  get a people/ page for who they are as a human)

## Slug convention
\`first-last.md\` — lowercase, hyphens for spaces.
Collisions: disambiguate (\`david-liu-crustdata.md\`).

## Sidecar
Per-person raw enrichment data lives in \`.raw/<slug>.json\`."

    _readme "companies" \
      "One page per organization (company, fund, nonprofit, gov body).

## What goes here
- Companies you do business with
- Funds you interact with
- Organizations relevant to your work

## What does NOT go here
- Individual people at the company → \`people/\` (cross-link both)
- A specific deal with the company → \`deals/\`
- Your own institution's strategy → \`org/\`

## Slug convention
\`company-name.md\` — lowercase, hyphens.

## Sidecar
Per-company raw enrichment data lives in \`.raw/<slug>.json\`."

    _readme "deals" \
      "Financial transactions with terms and a decision to make.

## What goes here
- Investment opportunities (rounds you're considering)
- Acquisitions, partnerships with financial terms
- Anything that requires a yes/no decision with money attached

## What does NOT go here
- The company doing the deal → \`companies/\` (cross-link)
- General company information without a transaction → \`companies/\`"

    _readme "meetings" \
      "Records of specific meetings/calls that happened at a specific time.

## What goes here
- Meeting transcripts with your analysis above the line
- Important calls with attendees and decisions

## What does NOT go here
- The people who attended → \`people/\` (cross-link)
- Recurring meeting templates → \`prompts/\`

## Slug convention
\`YYYY-MM-DD-meeting-topic.md\`"

    _readme "projects" \
      "Things being actively built — has a repo, spec, team, or active work.

## What goes here
- Software projects under development
- Initiatives with named owners and timelines
- Anything that has 'graduated' from idea to active work

## What does NOT go here
- Raw possibilities nobody is building → \`ideas/\`
- The major life domain the project sits in → \`programs/\`"

    _readme "ideas" \
      "Raw possibilities nobody is building yet.

## What goes here
- Speculative concepts you might pursue
- Things worth exploring but not yet committed to

## What does NOT go here
- Anything actively being built → \`projects/\`
- Mental models you'd teach as frameworks → \`concepts/\`

## Graduation
When someone starts working on an idea, move it to \`projects/\` and
keep a link from here pointing to the new project page."

    _readme "concepts" \
      "Reusable mental models, frameworks, theses about how the world works.

## What goes here
- Frameworks you'd teach in a professional talk
- Distilled mental models (~200 words of compiled truth)
- Theses about your domain

## What does NOT go here
- Developed prose / essays → \`writing/\`
- Private reflection → \`personal/\`
- Possibilities to build → \`ideas/\`"

    _readme "writing" \
      "Prose artifacts — essays, philosophy, drafts publishable as standalone work.

## What goes here
- Long-form essays
- Argument-driven prose
- Drafts of public writing

## What does NOT go here
- Distilled frameworks (~200 words) → \`concepts/\`
- Publication infrastructure or social monitoring → \`media/\`"

    _readme "programs" \
      "Major life workstreams — the forest, not the trees.

## What goes here
- Enduring domains of commitment that contain multiple projects
- Long-running themes (e.g., 'building company X', 'becoming healthier')

## What does NOT go here
- Specific projects within a program → \`projects/\` (cross-link)
- Your institution's strategy → \`org/\`"

    _readme "org" \
      "Your institution's strategy, org chart, processes, internal dynamics.

## What goes here
- Institutional strategy documents
- Internal processes and operations
- Your organization's structure

## What does NOT go here
- Your personal role or priorities within the org → \`programs/\`
- External companies → \`companies/\`"

    _readme "civic" \
      "Political landscape, policy, government, civic actors.

## What goes here
- Legislative agendas, policy debates
- Election context, government structure
- Civic positioning of political figures

## What does NOT go here
- The political figures themselves as humans → \`people/\` (cross-link)"

    _readme "media" \
      "Public narrative, content operations, social monitoring.

## What goes here
- Content production pipeline
- Social monitoring infrastructure
- Published posts and their performance

## What does NOT go here
- The essays themselves → \`writing/\`"

    _readme "personal" \
      "Private notes, health, personal reflection, inner life.

## What goes here
- Health logs, personal reflections
- Private thoughts not meant for sharing

## What does NOT go here
- Operational household stuff (PA would execute) → \`household/\`
- Anything you'd share in a professional talk → \`concepts/\`"

    _readme "household" \
      "Domestic operations — properties, logistics, household management.

## What goes here
- Property management, vendors, contractors
- Household logistics a PA would handle

## What does NOT go here
- Private reflections → \`personal/\`"

    _readme "hiring" \
      "Candidate pipelines and evaluations.

## What goes here
- Role specs
- Interview notes
- Active candidate evaluations

## What does NOT go here
- People you already hired → \`people/\`
- People you know but aren't evaluating → \`people/\`"

    _readme "sources" \
      "Raw data imports and archived snapshots.

## What goes here
- Bulk multi-entity imports (CSVs, JSON dumps)
- Periodic API exports
- Archive snapshots

## What does NOT go here
- Per-entity raw enrichment data → \`.raw/\` sidecar next to the entity"

    _readme "prompts" \
      "Reusable LLM prompt library.

## What goes here
- Templates for getting specific outputs from models
- Reusable system prompts

## What does NOT go here
- One-off prompts you used once → \`inbox/\` or discard"

    _readme "agent" \
      "Agent deliverables — briefings, digests, research the agent produced.

## What goes here
- Daily briefings
- Research reports
- Synthesized output the agent generated for your reading

## What does NOT go here
- Raw source material that fed the synthesis → \`sources/\`
- Notes you wrote → wherever they belong by subject"

    _readme "inbox" \
      "Unsorted quick captures (temporary).

## What goes here
- Things you don't yet know where to file
- Quick captures pending triage

## What does NOT go here
- Anything you DO know the home of — file it properly

If many items pile up here, it's a signal the schema needs to evolve."

    _readme "archive" \
      "Dead pages — no longer relevant, kept as historical record.

## What goes here
- Companies that died
- Ended relationships
- Resolved deals you want to remember
- Pages that no longer warrant compiled truth at the top

## What does NOT go here
- Active pages, even if dormant — keep them in their primary directory"

    # .raw/ subdirectories for the two highest-volume enrichment surfaces
    mkdir -p people/.raw companies/.raw
    touch people/.raw/.gitkeep companies/.raw/.gitkeep

    # ---- initial commit ----------------------------------------------------
    git add -A
    git commit -q -m "init: MECE brain template scaffolded by bootstrap-gbrain.sh

20 directories from docs/GBRAIN_RECOMMENDED_SCHEMA.md v0.5.0, each
with a README.md resolver, plus top-level RESOLVER.md + schema.md +
log.md + index.md and .raw/ sidecars under people/ + companies/."
  )
  log "Brain template scaffolded: 20 directories, 25 files, 1 commit."
}

[[ -n "${OPENROUTER_API_KEY:-}" ]] || fail "OPENROUTER_API_KEY is required (https://openrouter.ai/keys)" 1

gbrain_bootstrap_init_env
require_gbrain_installed

log "config: REPO=$REPO BRANCH=$BRANCH"
log "config: INSTALL_DIR=$INSTALL_DIR GBRAIN_HOME=$BRAIN_DATA"
log "Routing: embed=$GBRAIN_EMBEDDING_MODEL dims=$GBRAIN_EMBEDDING_DIMENSIONS"
log "Routing: chat=$GBRAIN_CHAT_MODEL expansion=$GBRAIN_EXPANSION_MODEL"

# -- Persist OpenRouter env for the agent process ------------------------------
PROFILE_FILE="/etc/profile.d/gbrain.sh"
if [[ -w "/etc/profile.d" ]] || [[ ! -e "$PROFILE_FILE" && -w "/etc" ]]; then
  cat > "$PROFILE_FILE" <<EOF
# gbrain — written by configure-gbrain.sh on $(date -u +%FT%TZ)
# Source: $REPO @ $BRANCH
export GBRAIN_HOME="$BRAIN_DATA"
export GBRAIN_EMBEDDING_MODEL="$GBRAIN_EMBEDDING_MODEL"
export GBRAIN_EMBEDDING_DIMENSIONS="$GBRAIN_EMBEDDING_DIMENSIONS"
export GBRAIN_CHAT_MODEL="$GBRAIN_CHAT_MODEL"
export GBRAIN_EXPANSION_MODEL="$GBRAIN_EXPANSION_MODEL"
case ":\$PATH:" in
  *":\$HOME/.bun/bin:"*) ;;
  *) export PATH="\$HOME/.bun/bin:\$PATH" ;;
esac
EOF
  chmod 0644 "$PROFILE_FILE"
  log "Persisted env to $PROFILE_FILE"
else
  log "warn: /etc/profile.d/ not writable; set env in k8s Deployment yaml instead"
fi

ENV_FILE="/etc/environment"
if [[ -w "$ENV_FILE" ]] || [[ ! -e "$ENV_FILE" && -w "/etc" ]]; then
  if [[ -e "$ENV_FILE" ]]; then
    sed -i.bak '/^# gbrain-bootstrap-begin/,/^# gbrain-bootstrap-end/d' "$ENV_FILE" 2>/dev/null || true
    rm -f "${ENV_FILE}.bak"
  fi
  cat >> "$ENV_FILE" <<EOF
# gbrain-bootstrap-begin (written $(date -u +%FT%TZ))
GBRAIN_HOME=$BRAIN_DATA
GBRAIN_EMBEDDING_MODEL=$GBRAIN_EMBEDDING_MODEL
GBRAIN_EMBEDDING_DIMENSIONS=$GBRAIN_EMBEDDING_DIMENSIONS
GBRAIN_CHAT_MODEL=$GBRAIN_CHAT_MODEL
GBRAIN_EXPANSION_MODEL=$GBRAIN_EXPANSION_MODEL
# gbrain-bootstrap-end
EOF
  log "Persisted env to $ENV_FILE"
fi

# -- Initialize the brain (idempotent) -----------------------------------------
BRAIN_DB="$BRAIN_DATA/.gbrain/brain.pglite"
if [[ ! -e "$BRAIN_DB" ]]; then
  log "Initializing brain at $BRAIN_DATA..."
  printf '\n' | gbrain init --pglite \
    --embedding-model "$GBRAIN_EMBEDDING_MODEL" \
    --embedding-dimensions "$GBRAIN_EMBEDDING_DIMENSIONS" \
    --expansion-model "$GBRAIN_EXPANSION_MODEL" \
    --chat-model "$GBRAIN_CHAT_MODEL" \
    || fail "gbrain init failed" 3
else
  log "Brain already initialized at $BRAIN_DATA (running migrations only)..."
  gbrain apply-migrations --yes >/dev/null 2>&1 || log "warn: apply-migrations exited non-zero; continuing"
fi

persist_gbrain_file_config

# -- Health checks -------------------------------------------------------------
log "Running gbrain doctor..."
gbrain doctor --json > "$BRAIN_DATA/last-doctor.json" || fail "gbrain doctor failed (see $BRAIN_DATA/last-doctor.json)" 3
log "doctor passed; report saved to $BRAIN_DATA/last-doctor.json"

probe_provider() {
  local touchpoint="$1"
  local model="$2"
  local logfile="$BRAIN_DATA/last-probe-$touchpoint.log"
  local exit_code=0

  log "Probing OpenRouter $touchpoint endpoint ($model)..."
  set +e
  gbrain providers test --touchpoint "$touchpoint" --model "$model" > "$logfile" 2>&1
  exit_code=$?
  set -e

  if [[ $exit_code -ne 0 ]]; then
    log "Probe exited non-zero ($exit_code). Captured output:"
    sed 's/^/    /' "$logfile" >&2
    fail "OpenRouter $touchpoint probe failed; see $logfile" 4
  fi

  if ! grep -q "All probes green" "$logfile"; then
    log "Probe exited 0 but did not print 'All probes green'. Captured output:"
    sed 's/^/    /' "$logfile" >&2
    fail "OpenRouter $touchpoint probe returned success-marker-missing; see $logfile" 4
  fi

  log "OpenRouter $touchpoint probe: OK"
}

probe_provider embedding "$GBRAIN_EMBEDDING_MODEL"
probe_provider chat      "$GBRAIN_CHAT_MODEL"

# -- Brain content -------------------------------------------------------------
BRAIN_CONTENT="$BRAIN_DATA/brain"

if [[ -n "${GBRAIN_BRAIN_REPO:-}" ]]; then
  BRAIN_CONTENT_BRANCH="${GBRAIN_BRAIN_BRANCH:-master}"
  if [[ ! -d "$BRAIN_CONTENT/.git" ]]; then
    log "Cloning brain content from $GBRAIN_BRAIN_REPO (branch $BRAIN_CONTENT_BRANCH)..."
    git clone --branch "$BRAIN_CONTENT_BRANCH" "$GBRAIN_BRAIN_REPO" "$BRAIN_CONTENT"
  else
    log "Pulling latest brain content from $GBRAIN_BRAIN_REPO..."
    git -C "$BRAIN_CONTENT" fetch origin "$BRAIN_CONTENT_BRANCH"
    git -C "$BRAIN_CONTENT" reset --hard "origin/$BRAIN_CONTENT_BRANCH"
  fi
elif [[ "${GBRAIN_NO_TEMPLATE:-0}" != "1" ]]; then
  scaffold_brain_template "$BRAIN_CONTENT"
else
  log "Skipping brain content (GBRAIN_BRAIN_REPO unset and GBRAIN_NO_TEMPLATE=1)"
fi

if [[ -d "$BRAIN_CONTENT" ]] && [[ -n "$(find "$BRAIN_CONTENT" -maxdepth 3 -name '*.md' -print -quit 2>/dev/null)" ]]; then
  log "Importing brain content (no-embed)..."
  gbrain import "$BRAIN_CONTENT" --no-embed
  log "Embedding stale chunks..."
  gbrain embed --stale || fail "gbrain embed --stale failed (check OPENROUTER_API_KEY and routing)" 3
  log "Brain content imported."
fi

VERIFY_SCRIPT="$INSTALL_DIR/scripts/verify-gbrain-openrouter-env.sh"
if [[ -x "$VERIFY_SCRIPT" ]]; then
  log "Running OpenRouter env verification..."
  GBRAIN_HOME="$BRAIN_DATA" "$VERIFY_SCRIPT" || fail "OpenRouter env verification failed; see output above" 3
else
  log "warn: $VERIFY_SCRIPT not found or not executable; skipping env verification"
fi

log "──────────────────────────────────────────"
log "GBrain configure complete."
log "  Install dir:  $INSTALL_DIR"
log "  Brain dir:    $BRAIN_DATA"
log "  Binary:       $(command -v gbrain)"
log "  Version:      $(gbrain --version 2>/dev/null || echo unknown)"
log "  Pages:        $(gbrain stats 2>/dev/null | grep -i 'page' | head -1 || echo 'gbrain stats failed')"
log "──────────────────────────────────────────"
log "Next: run 'gbrain serve --http --port 3131' or 'gbrain serve' for MCP."
